In [2]:
#Create Database Connection in Python
import pandas as pd
from sqlalchemy import create_engine

try:
    engine = create_engine("mysql+pymysql://root:Mysql@1234@localhost:3306/ecommerce")
    print("Connected successfully!")
except Exception as e:
    print("Connection error:", e)

Connected successfully!

In [3]:
import pandas as pd
import time
from sqlalchemy import create_engine, inspect

In [4]:
#Load Cleaned CSV 
import pandas as pd

df = pd.read_csv("C:/Users/Vedika Pingat/Downloads/ecommerce/ecommerce project/cleaned_data.csv")

print("CSV Loaded Successfully!")
print("Number of rows:", len(df))

CSV Loaded Successfully!
Number of rows: 401604

In [5]:
#Load Cleaned CSV into Database
from sqlalchemy import create_engine

username = "root"
password = "Mysql%401234"   # because of @
host = "localhost"
port = "3306"
database = "ecommerce_db"   # ✅ correct name

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

connection = engine.connect()
print("Connected successfully!")
connection.close()

Connected successfully!

In [6]:
from sqlalchemy import inspect

inspector = inspect(engine)
print("Tables in database:", inspector.get_table_names())

Tables in database: ['sales_data']

In [7]:
import pandas as pd

df = pd.read_csv("C:/Users/Vedika Pingat/Downloads/ecommerce/ecommerce project/cleaned_data.csv")

print("CSV Loaded:", len(df))

df.to_sql(
    name="sales_data",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data uploaded successfully!")

CSV Loaded: 401604
Data uploaded successfully!

In [8]:
from sqlalchemy import inspect

inspector = inspect(engine)
print("Tables:", inspector.get_table_names())

Tables: ['sales_data']

In [9]:
print(pd.read_sql("SELECT COUNT(*) AS total_rows FROM sales_data", engine))

   total_rows
0      401604

In [10]:
print(df.head())

  invoiceno stockcode                          description  quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

           invoicedate  unitprice  customerid         country  sales  \
0  2010-12-01 08:26:00       2.55     17850.0  United Kingdom  15.30
1  2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34
2  2010-12-01 08:26:00       2.75     17850.0  United Kingdom  22.00
3  2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34
4  2010-12-01 08:26:00       3.39     17850.0  United Kingdom  20.34

   Sales_Rank  revenue_per_unit  total_sales  year  month  high_value_order
0      2376.0              2.55        15.30  2010     12                 0
1      2261.0              3.39        20.34  2010     12                 0
2      2222.0              2.75        22.00  2010     12                 0
3      2261.0              3.39        20.34  2010     12                 0
4      2261.0              3.39        20.34  2010     12                 0

In [11]:
df.columns

Index(['invoiceno', 'stockcode', 'description', 'quantity', 'invoicedate',
       'unitprice', 'customerid', 'country', 'sales', 'Sales_Rank',
       'revenue_per_unit', 'total_sales', 'year', 'month', 'high_value_order'],
      dtype='object')

In [12]:
pd.read_sql("""
SELECT SUM(sales) AS Total_Revenue
FROM sales_data
""", engine)

   Total_Revenue
0   8.278519e+06

In [ ]:
#Shows total income generated.
#Helps management understand overall business growth.

In [13]:
pd.read_sql("""
SELECT COUNT(DISTINCT invoiceno) AS Total_Orders
FROM sales_data
""", engine)

   Total_Orders
0         22190

In [ ]:
#Shows total number of transactions.
#Helps measure business activity level.

In [14]:
pd.read_sql("""
SELECT country, SUM(sales) AS Revenue
FROM sales_data
GROUP BY country
ORDER BY Revenue DESC
""", engine)

                 country       Revenue
0         United Kingdom  6.747156e+06
1            Netherlands  2.846615e+05
2                   EIRE  2.500018e+05
3                Germany  2.215095e+05
4                 France  1.966260e+05
5              Australia  1.370098e+05
6            Switzerland  5.573940e+04
7                  Spain  5.475603e+04
8                Belgium  4.091096e+04
9                 Sweden  3.658541e+04
10                 Japan  3.534062e+04
11                Norway  3.516346e+04
12              Portugal  2.899576e+04
13               Finland  2.232674e+04
14       Channel Islands  2.007639e+04
15               Denmark  1.876814e+04
16                 Italy  1.689051e+04
17                Cyprus  1.285876e+04
18               Austria  1.015432e+04
19             Singapore  9.120390e+03
20                Poland  7.213140e+03
21                Israel  6.988400e+03
22                Greece  4.710520e+03
23               Iceland  4.310000e+03
24                Canada  3.666380e+03
25           Unspecified  2.660770e+03
26                 Malta  2.505470e+03
27  United Arab Emirates  1.902280e+03
28                   USA  1.730920e+03
29               Lebanon  1.693880e+03
30             Lithuania  1.661060e+03
31    European Community  1.291750e+03
32                Brazil  1.143600e+03
33                   RSA  1.002310e+03
34        Czech Republic  7.077200e+02
35               Bahrain  5.484000e+02
36          Saudi Arabia  1.311700e+02

In [ ]:
#Identifies strongest performing countries.
#Helps business focus on profitable markets.

In [15]:
pd.read_sql("""
SELECT description, SUM(quantity) AS Total_Quantity_Sold
FROM sales_data
GROUP BY description
ORDER BY Total_Quantity_Sold DESC

""", engine)

                              description  Total_Quantity_Sold
0       WORLD WAR 2 GLIDERS ASSTD DESIGNS              53119.0
1                 JUMBO BAG RED RETROSPOT              44963.0
2           ASSORTED COLOUR BIRD ORNAMENT              35215.0
3      WHITE HANGING HEART T-LIGHT HOLDER              34128.0
4         PACK OF 72 RETROSPOT CAKE CASES              33386.0
...                                   ...                  ...
3891      PINK POODLE HANGING DECORATION                 -12.0
3892                      CRUK Commission                -16.0
3893      ASSORTED TUTTI FRUTTI ROUND BOX                -24.0
3894                             Discount              -1194.0
3895  ROTATING SILVER ANGELS T-LIGHT HLDR              -1475.0

[3896 rows x 2 columns]

In [ ]:
#Shows most profitable products.
#Important for pricing and marketing strategy

In [17]:
pd.read_sql("""
SELECT year, month, SUM(sales) AS Monthly_Revenue
FROM sales_data
GROUP BY year, month
ORDER BY year, month
""", engine)

    year  month  Monthly_Revenue
0   2010     12       552372.860
1   2011      1       473731.900
2   2011      2       435534.070
3   2011      3       578576.210
4   2011      4       425222.671
5   2011      5       647011.670
6   2011      6       606862.520
7   2011      7       573112.321
8   2011      8       615078.090
9   2011      9       929356.232
10  2011     10       973306.380
11  2011     11      1126815.070
12  2011     12       341539.430

In [18]:
#identifies seasonal trends.
#Helps forecast future sales

In [43]:
pd.read_sql("""
SELECT high_value_order, COUNT(*) AS Order_Count
FROM sales_data
GROUP BY high_value_order
""", engine)

   high_value_order  Order_Count
0                 0       401289
1                 1          315

In [ ]:
#Shows how many premium orders exist.
#Helps identify high-value customers.

In [44]:
pd.read_sql("""
SELECT AVG(total_sales) AS Avg_Order_Value
FROM sales_data
""", engine)

   Avg_Order_Value
0        20.613638

In [ ]:
#Shows spending behavior of customers.
#Higher value = better profitability.

In [45]:
pd.read_sql("""
SELECT customerid, SUM(sales) AS Total_Spent
FROM sales_data
GROUP BY customerid
ORDER BY Total_Spent DESC
LIMIT 10
""", engine)

   customerid  Total_Spent
0     14646.0    279489.02
1     18102.0    256438.49
2     17450.0    187322.17
3     14911.0    132458.73
4     12415.0    123725.45
5     14156.0    113214.59
6     17511.0     88125.38
7     16684.0     65892.08
8     13694.0     62690.54
9     15311.0     59284.19

In [ ]:
#Identifies loyal / VIP customers.
#Useful for retention strategies.

In [20]:
pd.read_sql("""
SELECT description, AVG(revenue_per_unit) AS Avg_Revenue_Per_Unit
FROM sales_data
GROUP BY description
ORDER BY Avg_Revenue_Per_Unit DESC
LIMIT 10
""", engine)

                          description  Avg_Revenue_Per_Unit
0                      DOTCOM POSTAGE            744.147500
1      PICNIC BASKET WICKER 60 PIECES            649.500000
2                     CRUK Commission            495.839375
3                              Manual            338.044391
4        REGENCY MIRROR WITH SHUTTERS            156.428571
5  RUSTIC  SEVENTEEN DRAWER SIDEBOARD            156.034483
6         VINTAGE RED KITCHEN CABINET            150.663043
7        VINTAGE BLUE KITCHEN CABINET            143.653846
8       CHEST NATURAL WOOD 20 DRAWERS            118.076923
9       LOVE SEAT ANTIQUE WHITE METAL            115.388889

In [ ]:
#Identifies premium-priced products.
#Useful for margin optimization.

In [21]:
pd.read_sql("""
SELECT COUNT(*) AS Returned_Orders
FROM sales_data
WHERE quantity < 0
""", engine)

   Returned_Orders
0             8872

In [ ]:
#Shows return rate.
#High returns = product or quality issue.

In [22]:
import time

# ---- PANDAS ----
start = time.time()

df.groupby("country")["sales"].sum()

pandas_time = time.time() - start
print("Pandas Time:", pandas_time)


# ---- SQL ----
start = time.time()

pd.read_sql("""
SELECT country, SUM(sales)
FROM sales_data
GROUP BY country
""", engine)

sql_time = time.time() - start
print("SQL Time:", sql_time)

Pandas Time: 0.03305459022521973
SQL Time: 0.4408750534057617

In [23]:
#Create Function
def get_total_revenue():
    query = "SELECT SUM(sales) AS Total_Revenue FROM sales_data"
    result = pd.read_sql(query, engine)
    return result

In [24]:
print(get_total_revenue())

   Total_Revenue
0   8.278519e+06

In [25]:
def get_top_customers():
    query = """
    SELECT customerid, SUM(sales) AS Total_Spent
    FROM sales_data
    GROUP BY customerid
    ORDER BY Total_Spent DESC
    LIMIT 5
    """
    result = pd.read_sql(query, engine)
    return result

In [55]:
print(get_top_customers())

   customerid  Total_Spent
0     14646.0    279489.02
1     18102.0    256438.49
2     17450.0    187322.17
3     14911.0    132458.73
4     12415.0    123725.45

In [27]:
#Error Handling
try:
   

    print(get_total_revenue())
    print(get_top_customers())

    print("\nAll queries executed successfully!")

except Exception as e:
    print("Error occurred:", e)

finally:
    engine.dispose()
    print("Database connection closed.")

   Total_Revenue
0   8.278519e+06
   customerid  Total_Spent
0     14646.0    279489.02
1     18102.0    256438.49
2     17450.0    187322.17
3     14911.0    132458.73
4     12415.0    123725.45

All queries executed successfully!
Database connection closed.