In [ ]:
# Data Cleaning Mini-Project

## Objective
Transform raw dataset into an analysis-ready clean dataset by:
- Handling missing values
- Removing duplicates
- Detecting and treating outliers
- Standardizing categorical values
- Converting date columns
- Generating a data quality report

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [2]:
import os
os.getcwd()

'C:\\Users\\Vedika Pingat'

In [3]:
import os
print(os.path.exists("C:/Users/Vedika Pingat/Downloads/ecommerce/data.csv"))

True

In [4]:
import pandas as pd

# Define file path
file_path = "C:/Users/Vedika Pingat/Downloads/ecommerce/data.csv"

# Load dataset with proper encoding
df = pd.read_csv(file_path, encoding="latin1", low_memory=False)

# Display first 5 rows
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [ ]:
## Initial Data Assessment
- Number of rows and columns
- Missing values
- Duplicate rows
- Basic statistics

In [5]:
print("Dataset Shape:", df.shape)
df.info()

Dataset Shape: (541909, 8)
<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [6]:
#missing values
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [9]:
rows_before = df.shape[0]
cols_before = df.shape[1]
null_before = df.isnull().sum().sum()
duplicates_before = df.duplicated().sum()

print("Total Missing Values Before Cleaning:", null_before)
print("Total Duplicate Rows Before Cleaning:", duplicates_before)

Total Missing Values Before Cleaning: 136534
Total Duplicate Rows Before Cleaning: 5268

In [ ]:
#handle missing values

In [11]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [12]:
## Example: drop rows if a key column is missing
# Drop rows where CustomerID or Description is missing
df = df.dropna(subset=['CustomerID', 'Description'])

print("Shape after dropping critical missing rows:", df.shape)

Shape after dropping critical missing rows: (406829, 8)

In [15]:
#Fill Numerical Missing Values
numeric_cols = ['Quantity', 'UnitPrice']

for col in numeric_cols:
    df[col].fillna(df[col].median(), inplace=True)

print("Missing values after numeric filling:")
df[numeric_cols].isnull().sum()

Missing values after numeric filling:

C:\Users\Vedika Pingat\AppData\Local\Temp\ipykernel_3024\1215317728.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Vedika Pingat\AppData\Local\Temp\ipykernel_3024\1215317728.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)

Quantity     0
UnitPrice    0
dtype: int64

In [17]:
#forward fill
df['InvoiceDate'] = df['InvoiceDate'].ffill()

print("Missing values in InvoiceDate:", df['InvoiceDate'].isnull().sum())

Missing values in InvoiceDate: 0

In [18]:

df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [19]:
## Removing Duplicate Rows
df = df.drop_duplicates()

In [21]:
# Handling Invalid Values and Outliers
print("Negative Quantity Count:", (df['Quantity'] < 0).sum())
print("Zero Quantity Count:", (df['Quantity'] == 0).sum())
print("Negative UnitPrice Count:", (df['UnitPrice'] < 0).sum())
print("Zero UnitPrice Count:", (df['UnitPrice'] == 0).sum())

Negative Quantity Count: 8872
Zero Quantity Count: 0
Negative UnitPrice Count: 0
Zero UnitPrice Count: 40

In [22]:
df[df['Quantity'] <= 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,12/9/2011 9:57,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,12/9/2011 10:28,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,12/9/2011 11:57,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,12/9/2011 11:58,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,12/9/2011 11:58,1.25,17315.0,United Kingdom

In [23]:
df[df['UnitPrice'] <= 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,12/5/2010 14:02,0.0,12647.0,Germany
33576,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,12/16/2010 14:36,0.0,16560.0,United Kingdom
40089,539722,22423,REGENCY CAKESTAND 3 TIER,10,12/21/2010 13:45,0.0,14911.0,EIRE
47068,540372,22090,PAPER BUNTING RETROSPOT,24,1/6/2011 16:41,0.0,13081.0,United Kingdom
47070,540372,22553,PLASTERS IN TIN SKULLS,24,1/6/2011 16:41,0.0,13081.0,United Kingdom

In [24]:
# Remove negative or zero quantity
df = df[df['Quantity'] > 0]

# Remove negative or zero unit price
df = df[df['UnitPrice'] > 0]

print("Shape after removing invalid Quantity and UnitPrice:", df.shape)

Shape after removing invalid Quantity and UnitPrice: (392692, 8)

In [25]:
#IQR Outlier Removal advance cleaning
def remove_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return data[(data[column] >= lower) & (data[column] <= upper)]

In [26]:
df = remove_outliers_iqr(df, 'Quantity')
df = remove_outliers_iqr(df, 'UnitPrice')

print("Shape after IQR outlier removal:", df.shape)

Shape after IQR outlier removal: (333234, 8)

In [27]:
#Standardize Categorical Data
 #Convert text to lowercase, Remove extra spaces, Ensure consistent formatting
df['Description'] = df['Description'].str.strip().str.lower()
df['Country'] = df['Country'].str.strip().str.lower()
df['StockCode'] = df['StockCode'].str.strip()

In [28]:
## Converting InvoiceDate to Datetime Format
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

print(df['InvoiceDate'].dtype)

datetime64[us]

In [29]:
df['InvoiceDate']

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 333234, dtype: datetime64[us]

In [30]:
#Create Data Quality Report
rows_after = df.shape[0]
cols_after = df.shape[1]
null_after = df.isnull().sum().sum()
duplicates_after = df.duplicated().sum()

report = pd.DataFrame({
    "Metric": ["Rows", "Columns", "Missing Values", "Duplicate Rows"],
    "Before Cleaning": [rows_before, cols_before, null_before, duplicates_before],
    "After Cleaning": [rows_after, cols_after, null_after, duplicates_after]
})

report

           Metric  Before Cleaning  After Cleaning
0            Rows           541909          333234
1         Columns                8               8
2  Missing Values           136534               0
3  Duplicate Rows             5268               0

In [31]:
#missing vakue reduction 
reduction = ((null_before - null_after) / null_before) * 100
print("Missing Values Reduced By:", round(reduction, 2), "%")

Missing Values Reduced By: 100.0 %

In [35]:
df.to_csv("cleaned_dataset.csv", index=False)

print("exported")

exported